endpoint: wss://kusama-rpc.polkadot.io
mock-signature-host: true
block: ${env.KUSAMA_BLOCK_NUMBER}
db: ./db.sqlite
runtime-log-level: 5

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: '10000000000000000000'
      -
        -
          - 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
        - providers: 1
          data:
            free: '10000000000000000000'
      -
        -
          - 5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y
        - providers: 1
          data:
            free: '10000000000000000000'
  Society:
    $removePrefix:
      - Bids
      - Candidates
      - Members
    Bids:
      - { who: "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY", kind: "deposit", value: 1 } # Alice
    Candidates:
      - [[5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty]] # Bob
    Members:
      - [[5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y], rank: 0] # Charlie
  ParasDisputes:
    $removePrefix: ['disputes'] # those can makes block building super slow
  # Configuration:
  #   ActiveConfig: {
  #     "maxCodeSize": 10485760,
  #     "maxHeadDataSize": 20480,
  #     "maxUpwardQueueCount": 10,
  #     "maxUpwardQueueSize": 51200,
  #     "maxUpwardMessageSize": 51200,
  #     "maxUpwardMessageNumPerCandidate": 10,
  #     "hrmpMaxMessageNumPerCandidate": 10,
  #     "validationUpgradeCooldown": 3600,
  #     "validationUpgradeDelay": 600,
  #     "maxPovSize": 5242880,
  #     "maxDownwardMessageSize": 51200,
  #     "umpServiceTotalWeight": {
  #       "refTime": 100000000000,
  #       "proofSize": 5242880
  #     },
  #     "hrmpMaxParachainOutboundChannels": 30,
  #     "hrmpMaxParathreadOutboundChannels": 0,
  #     "hrmpSenderDeposit": 5000000000000,
  #     "hrmpRecipientDeposit": 5000000000000,
  #     "hrmpChannelMaxCapacity": 1000,
  #     "hrmpChannelMaxTotalSize": 102400,
  #     "hrmpMaxParachainInboundChannels": 30,
  #     "hrmpMaxParathreadInboundChannels": 0,
  #     "hrmpChannelMaxMessageSize": 102400,
  #     "codeRetentionPeriod": 28800,
  #     "parathreadCores": 0,
  #     "parathreadRetries": 0,
  #     "groupRotationFrequency": 10,
  #     "chainAvailabilityPeriod": 10,
  #     "threadAvailabilityPeriod": 10,
  #     "schedulingLookahead": 1,
  #     "maxValidatorsPerCore": 5,
  #     "maxValidators": 200,
  #     "disputePeriod": 6,
  #     "disputePostConclusionAcceptancePeriod": 600,
  #     "disputeConclusionByTimeOutPeriod": 600,
  #     "noShowSlots": 2,
  #     "nDelayTranches": 89,
  #     "zerothDelayTrancheWidth": 0,
  #     "neededApprovals": 30,
  #     "relayVrfModuloSamples": 40,
  #     "umpMaxIndividualWeight": {
  #       "refTime": 50000000000,
  #       "proofSize": 5242880
  #     },
  #     "pvfCheckingEnabled": true,
  #     "pvfVotingTtl": 2,
  #     "minimumValidationUpgradeDelay": 20
  #   }
